main/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'umapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('umagirl/list/', views.UmaGirlListView.as_view(), name="UmaGirlList"),
    path('umagirl/<slug:slug>', views.UmaGirlDetailView.as_view(), name="UmaGirlDetail")
]

umapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from django.template.defaultfilters import slugify


class UmaGirl(models.Model):
    name = models.CharField(
        verbose_name="名前",
        max_length=200,
        help_text="",
    )

    nameEN = models.CharField(
        verbose_name="名前(英語)",
        max_length=200,
        help_text="",
    )

    birthday = models.DateField(
        verbose_name="誕生日",
        help_text="",
    )

    height = models.PositiveSmallIntegerField(
        verbose_name="身長",
        validators=[
            MinValueValidator(140),
            MaxValueValidator(200),
        ]
    )

    weight = models.CharField(
        verbose_name="体重",
        max_length=200,
        help_text="",
    )

    breast = models.PositiveSmallIntegerField(
        verbose_name="胸囲",
        validators=[
            MinValueValidator(70),
            MaxValueValidator(120),
        ]
    )

    waist = models.PositiveSmallIntegerField(
        verbose_name="腰囲",
        validators=[
            MinValueValidator(40),
            MaxValueValidator(100),
        ]
    )

    hip = models.PositiveSmallIntegerField(
        verbose_name="臀囲",
        validators=[
            MinValueValidator(70),
            MaxValueValidator(120),
        ]
    )

    icon = models.ImageField(
        verbose_name="アイコン",
        upload_to='icons/',
        null=True,
        blank=True,
    )

    draftImage = models.ImageField(
        verbose_name="原案",
        upload_to='draftImage/',
        null=True,
        blank=True,
    )

    memo = models.TextField(
        verbose_name="備考",
    )

    slug = models.SlugField(
        null=True,
        blank=True,
        unique=True,
    )

    def __str__(self):
        return "%s" % self.name

    def get_absolute_url(self):
        return reverse('umapp:UmaGirlDetail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            n = self.nameEN.replace(' ', '_')
            self.slug = slugify(n)
        return super().save(*args, **kwargs)

main/views.py
from django.views import generic
from .models import UmaGirl


class IndexView(generic.TemplateView):
    template_name = "index.html"


class UmaGirlListView(generic.ListView):
    model = UmaGirl
    template_name = r"umaGirl\UmaGirlsList.html"


class UmaGirlDetailView(generic.DetailView):
    model = UmaGirl
    template_name = r"umaGirl\UmaGirlDetail.html"

templates/base.html
<!doctype html>
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='Full' %}

<html lang="ja">
<head>
    <meta charset="UTF-8">

    <title>ウマ娘管理APP</title>
</head>
<header>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'umapp:index' %}">ウマ娘管理APP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home<span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'umapp:UmaGirlList' %}">ウマ娘一覧</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
</header>

<body>
<div class="container mt-3 mb-3">
    {% block Content %}
    {% endblock Content %}
</div>
</body>


<footer>
    <nav class="navbar fixed-bottom navbar-dark bg-dark">
        <a class="navbar-brand" href="#">aaa</a>
    </nav>
</footer>
</html>

templates/index.html
{% extends "base.html" %}

{% block Content %}
    <a href="{% url 'umapp:UmaGirlList' %}" class="btn btn-sm btn-primary">ウマ娘</a>
{% endblock %}

templates/umaGirl/UmaGirlDetail.html
{% extends "base.html" %}

{% block Content %}
    <div class="row">
        <div class="col-sm-6">
            <img class="card-img" src="/media/{{ umagirl.draftImage }}" alt="{{ umagirl.name }}">
        </div>
        <div class="col-sm-6">
            <h5>{{ umagirl.nameEN }}</h5>
            <h3>{{ umagirl.name }}</h3>
            <hr>
            <div class="row">
                <div class="col-4">
                    誕生日
                </div>
                <div class="col-8">
                    {{ umagirl.birthday | date:"n月j日" }}
                </div>

                <div class="col-4">
                    身長
                </div>
                <div class="col-8">
                    {{ umagirl.height }}cm
                </div>

                <div class="col-4">
                    体重
                </div>
                <div class="col-8">
                    {{ umagirl.weight }}
                </div>

                <div class="col-4">
                    スリーサイズ
                </div>
                <div class="col-8">
                    B{{ umagirl.breast }}・W{{ umagirl.waist }}・H{{ umagirl.hip }}
                </div>
            </div>
            <hr>
            {{ umagirl.memo | linebreaksbr }}
            <hr>
        </div>

    </div>
{% endblock %}

templates/umaGirl/UmaGirlsList.html
{% extends "base.html" %}

{% block Content %}
    <div class="row">

        {% for umagirl in umagirl_list %}
            <div class="col-md-4 col-lg-3">
                {{ umagi.name }}
                <div class="card">
                    <a href="{{ umagirl.get_absolute_url }}">
                        <img class="card-img-top" src="/media/{{ umagirl.icon }}" alt="{{ umagirl.name }}">
                    </a>
                    <div class="card-body">
                        <p class="card-text">{{ umagirl.name }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}